# De Jesus, Samantha I.
# Partosa, Sebastian D.V.

# DATA CLEANING

In [77]:
import numpy as np #for numerical computation
import matplotlib.pyplot as plot #calling the library matplotlib specific the
import pandas as pd #to manipulate data ex. slicing

In [78]:
dataset=pd.read_csv('Data.csv')
print(dataset.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain   NaN  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

In [79]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain   NaN  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

In [80]:
dataset.shape

(10, 4)

In [81]:
dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [82]:
dataset.describe()

            Age        Salary
count   8.00000      9.000000
mean   37.50000  60777.777778
std     6.88684  11344.357383
min    27.00000  48000.000000
25%    33.75000  52000.000000
50%    38.00000  58000.000000
75%    41.00000  67000.000000
max    48.00000  83000.000000

In [83]:
dataset.isnull().sum().sort_values(ascending=False)

Age          2
Salary       1
Country      0
Purchased    0
dtype: int64

In [84]:
dataset=pd.read_csv('Data.csv')

In [85]:
new_dataset=dataset.dropna()
print(new_dataset.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

In [86]:
new_dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

In [87]:
#Remove all rows with NULL values:
data1=pd.read_csv('Data.csv')
data1.dropna(inplace= True)
print(data1.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

In [88]:
#Replace NULL values with the number 50000:
data2 = pd.read_csv('Data.csv')
data2.fillna(50000, inplace = True)
print(data2.to_string())

   Country      Age   Salary Purchased
0   France     44.0  72000.0        No
1    Spain  50000.0  48000.0       Yes
2  Germany     30.0  54000.0        No
3    Spain     38.0  61000.0        No
4  Germany     40.0  50000.0       Yes
5   France     35.0  58000.0       Yes
6    Spain  50000.0  52000.0        No
7   France     48.0  52000.0       Yes
8  Germany     38.0  83000.0        No
9   France     27.0  67000.0       Yes

In [89]:
#Replace NULL values in the "Salary" columns with the number 50,000:
data3 = pd.read_csv('Data.csv')
data3["Salary"].fillna(50000, inplace = True)
print(data3.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain   NaN  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  50000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\3803159319.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3["Salary"].fillna(50000, inplace = True)

In [90]:
#Replace NULL values in the "Age" columns with the number 36:
data3 = pd.read_csv('Data.csv')
data3["Age"].fillna(36, inplace = True)
data3["Salary"].fillna(50000, inplace = True)
print(data3.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  36.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  50000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  36.0  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\1655443686.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3["Age"].fillna(36, inplace = True)
C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\1655443686.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data3["Salary"].fillna(50000, inplace = True)

In [91]:
data4 = pd.read_csv('Data.csv')
data4.describe()

            Age        Salary
count   8.00000      9.000000
mean   37.50000  60777.777778
std     6.88684  11344.357383
min    27.00000  48000.000000
25%    33.75000  52000.000000
50%    38.00000  58000.000000
75%    41.00000  67000.000000
max    48.00000  83000.000000

In [109]:
#Calculate the MEAN, and replace any empty values with it:
data4 = pd.read_csv('Data.csv')
x=data4["Salary"].mean()
xx=data4["Age"].mean()
data4["Salary"].fillna(x, inplace=True)
data4["Age"].fillna(xx, inplace=True)
print(data4.to_string())

   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  37.5  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  60777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  37.5  52000.000000        No
7   France  48.0  52000.000000       Yes
8  Germany  38.0  83000.000000        No
9   France  27.0  67000.000000       Yes

C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\3440833117.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data4["Salary"].fillna(x, inplace=True)
C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\3440833117.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data4["Age"].fillna(xx, inplace=True)

In [113]:
data5 = pd.read_csv('Data.csv')

In [115]:
#Calculate the MEDIAN, and replace any empty values with it:
C=data5["Age"].median()
D=data5["Salary"].median()
data5["Age"].fillna(C,inplace=True)
data5["Salary"].fillna(D,inplace=True)
print(data5.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  38.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  58000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\713912393.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data5["Age"].fillna(C,inplace=True)
C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\713912393.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data5["Salary"].fillna(D,inplace=True)

In [117]:
#Calculate the MODE, and replace any empty values with it:
data6 = pd.read_csv('Data.csv')
E=data6["Age"].mode()[0]
F=data6["Salary"].mode()[0]
data6["Age"].fillna(E, inplace = True)
data6["Salary"].fillna(F, inplace = True)
print(data6.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  38.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  52000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  38.0  52000.0        No
7   France  48.0  52000.0       Yes
8  Germany  38.0  83000.0        No
9   France  27.0  67000.0       Yes

C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\4188319475.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data6["Age"].fillna(E, inplace = True)
C:\Users\sayde\AppData\Local\Temp\ipykernel_7292\4188319475.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data6["Salary"].fillna(F, inplace = True)

In [119]:
E

38.0

In [121]:
F

52000.0

# DATA PREPROCESSING

In [131]:
#Importing the libraries #to execute CTRL+enter
import numpy as np #for numerical computation
import matplotlib.pyplot as plot #calling the library matplotlib specific the
import pandas as pd #to manipulate data ex slicing

In [127]:
#Import the Dataset
data_co2=pd.read_csv('data_co2.csv')
print(data_co2.to_string())

           Car       Model  Volume  Weight  CO2
0       Toyoty        Aygo    1000     790   99
1   Mitsubishi  Space Star    1200    1160   95
2        Skoda      Citigo    1000     929   95
3         Fiat         500     900     865   90
4         Mini      Cooper    1500    1140  105
5           VW         Up!    1000     929  105
6        Skoda       Fabia    1400    1109   90
7     Mercedes     A-Class    1500    1365   92
8         Ford      Fiesta    1500    1112   98
9         Audi          A1    1600    1150   99
10     Hyundai         I20    1100     980   99
11      Suzuki       Swift    1300     990  101
12        Ford      Fiesta    1000    1112   99
13       Honda       Civic    1600    1252   94
14      Hundai         I30    1600    1326   97
15        Opel       Astra    1600    1330   97
16         BMW           1    1600    1365   99
17       Mazda           3    2200    1280  104
18       Skoda       Rapid    1600    1119  104
19        Ford       Focus    2000    1328  105
20        Ford      Mondeo    1600    1584   94
21        Opel    Insignia    2000    1428   99
22    Mercedes     C-Class    2100    1365   99
23       Skoda     Octavia    1600    1415   99
24       Volvo         S60    2000    1415   99
25    Mercedes         CLA    1500    1465  102
26        Audi          A4    2000    1490  104
27        Audi          A6    2000    1725  114
28       Volvo         V70    1600    1523  109
29         BMW           5    2000    1705  114
30    Mercedes     E-Class    2100    1605  115
31       Volvo        XC70    2000    1746  117
32        Ford       B-Max    1600    1235  104
33         BMW         216    1600    1390  108
34        Opel      Zafira    1600    1405  109
35    Mercedes         SLK    2500    1395  120

In [129]:
data_co2.describe()

            Volume       Weight         CO2
count    36.000000    36.000000   36.000000
mean   1611.111111  1292.277778  102.027778
std     388.975047   242.123889    7.454571
min     900.000000   790.000000   90.000000
25%    1475.000000  1117.250000   97.750000
50%    1600.000000  1329.000000   99.000000
75%    2000.000000  1418.250000  105.000000
max    2500.000000  1746.000000  120.000000

In [134]:
#We can use Volume & Weight to Predict CO2
#Independent Variable:
x=data_co2[['Weight','Volume']]
x

    Weight  Volume
0      790    1000
1     1160    1200
2      929    1000
3      865     900
4     1140    1500
5      929    1000
6     1109    1400
7     1365    1500
8     1112    1500
9     1150    1600
10     980    1100
11     990    1300
12    1112    1000
13    1252    1600
14    1326    1600
15    1330    1600
16    1365    1600
17    1280    2200
18    1119    1600
19    1328    2000
20    1584    1600
21    1428    2000
22    1365    2100
23    1415    1600
24    1415    2000
25    1465    1500
26    1490    2000
27    1725    2000
28    1523    1600
29    1705    2000
30    1605    2100
31    1746    2000
32    1235    1600
33    1390    1600
34    1405    1600
35    1395    2500

In [136]:
#Dependent variable:
y=data_co2['CO2']
y

0      99
1      95
2      95
3      90
4     105
5     105
6      90
7      92
8      98
9      99
10     99
11    101
12     99
13     94
14     97
15     97
16     99
17    104
18    104
19    105
20     94
21     99
22     99
23     99
24     99
25    102
26    104
27    114
28    109
29    114
30    115
31    117
32    104
33    108
34    109
35    120
Name: CO2, dtype: int64

In [138]:
print(x.to_string())

    Weight  Volume
0      790    1000
1     1160    1200
2      929    1000
3      865     900
4     1140    1500
5      929    1000
6     1109    1400
7     1365    1500
8     1112    1500
9     1150    1600
10     980    1100
11     990    1300
12    1112    1000
13    1252    1600
14    1326    1600
15    1330    1600
16    1365    1600
17    1280    2200
18    1119    1600
19    1328    2000
20    1584    1600
21    1428    2000
22    1365    2100
23    1415    1600
24    1415    2000
25    1465    1500
26    1490    2000
27    1725    2000
28    1523    1600
29    1705    2000
30    1605    2100
31    1746    2000
32    1235    1600
33    1390    1600
34    1405    1600
35    1395    2500

In [143]:
print(y.to_string())

0      99
1      95
2      95
3      90
4     105
5     105
6      90
7      92
8      98
9      99
10     99
11    101
12     99
13     94
14     97
15     97
16     99
17    104
18    104
19    105
20     94
21     99
22     99
23     99
24     99
25    102
26    104
27    114
28    109
29    114
30    115
31    117
32    104
33    108
34    109
35    120

# Build Multiple Linear Regression Model

In [146]:
#Import Library
from sklearn import linear_model

In [154]:
mlr_model = linear_model.LinearRegression()
mlr_model.fit(x,y)

LinearRegression()

In [160]:
#predict the CO2 emission of a car where the weight is 2300kg, and the volume
predictedCO2=mlr_model.predict([[2300,1300]])
predictedCO2

C:\Users\sayde\New folder\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([107.2087328])

In [164]:
print(predictedCO2)

[107.2087328]

In [168]:
data_co2.describe()

            Volume       Weight         CO2
count    36.000000    36.000000   36.000000
mean   1611.111111  1292.277778  102.027778
std     388.975047   242.123889    7.454571
min     900.000000   790.000000   90.000000
25%    1475.000000  1117.250000   97.750000
50%    1600.000000  1329.000000   99.000000
75%    2000.000000  1418.250000  105.000000
max    2500.000000  1746.000000  120.000000

# SCALE FEATURES / FEATURE SCALING

In [172]:
#Scale all values in the Weight and Volume Columns:
#Import Libraries
import pandas
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
scale

StandardScaler()

In [174]:
#Independent Variable
X1=data_co2[['Weight','Volume']]
X1

    Weight  Volume
0      790    1000
1     1160    1200
2      929    1000
3      865     900
4     1140    1500
5      929    1000
6     1109    1400
7     1365    1500
8     1112    1500
9     1150    1600
10     980    1100
11     990    1300
12    1112    1000
13    1252    1600
14    1326    1600
15    1330    1600
16    1365    1600
17    1280    2200
18    1119    1600
19    1328    2000
20    1584    1600
21    1428    2000
22    1365    2100
23    1415    1600
24    1415    2000
25    1465    1500
26    1490    2000
27    1725    2000
28    1523    1600
29    1705    2000
30    1605    2100
31    1746    2000
32    1235    1600
33    1390    1600
34    1405    1600
35    1395    2500

In [176]:
#Dependent Variable
y=data_co2['CO2']
y

0      99
1      95
2      95
3      90
4     105
5     105
6      90
7      92
8      98
9      99
10     99
11    101
12     99
13     94
14     97
15     97
16     99
17    104
18    104
19    105
20     94
21     99
22     99
23     99
24     99
25    102
26    104
27    114
28    109
29    114
30    115
31    117
32    104
33    108
34    109
35    120
Name: CO2, dtype: int64

In [186]:
#Feature Scale the Independent Variable
scaledX1=scale.fit_transform(X1)
print(scaledX1)

[[-2.10389253 -1.59336644]
 [-0.55407235 -1.07190106]
 [-1.52166278 -1.59336644]
 [-1.78973979 -1.85409913]
 [-0.63784641 -0.28970299]
 [-1.52166278 -1.59336644]
 [-0.76769621 -0.55043568]
 [ 0.3046118  -0.28970299]
 [-0.7551301  -0.28970299]
 [-0.59595938 -0.0289703 ]
 [-1.30803892 -1.33263375]
 [-1.26615189 -0.81116837]
 [-0.7551301  -1.59336644]
 [-0.16871166 -0.0289703 ]
 [ 0.14125238 -0.0289703 ]
 [ 0.15800719 -0.0289703 ]
 [ 0.3046118  -0.0289703 ]
 [-0.05142797  1.53542584]
 [-0.72580918 -0.0289703 ]
 [ 0.14962979  1.01396046]
 [ 1.2219378  -0.0289703 ]
 [ 0.5685001   1.01396046]
 [ 0.3046118   1.27469315]
 [ 0.51404696 -0.0289703 ]
 [ 0.51404696  1.01396046]
 [ 0.72348212 -0.28970299]
 [ 0.8281997   1.01396046]
 [ 1.81254495  1.01396046]
 [ 0.96642691 -0.0289703 ]
 [ 1.72877089  1.01396046]
 [ 1.30990057  1.27469315]
 [ 1.90050772  1.01396046]
 [-0.23991961 -0.0289703 ]
 [ 0.40932938 -0.0289703 ]
 [ 0.47215993 -0.0289703 ]
 [ 0.4302729   2.31762392]]

In [188]:
#Predict the CO2 emission from a 1.3 liter car that weighs 2300 kilograms:
mlr = linear_model.LinearRegression()
mlr.fit(scaledX1,y)

LinearRegression()

In [190]:
scaled=scale.transform([[2300,1.3]])
predictedCO2=mlr.predict([scaled[0]])
print(predictedCO2)

[97.07204485]

C:\Users\sayde\New folder\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

# CATEGORICAL DATA

In [193]:
#One Hot Encode the Car Column:
ohe_data_co2=pd.get_dummies(data_co2[['Car']])
print(ohe_data_co2.to_string())
ohe_data_co2

    Car_Audi  Car_BMW  Car_Fiat  Car_Ford  Car_Honda  Car_Hundai  Car_Hyundai  Car_Mazda  Car_Mercedes  Car_Mini  Car_Mitsubishi  Car_Opel  Car_Skoda  Car_Suzuki  Car_Toyoty  Car_VW  Car_Volvo
0      False    False     False     False      False       False        False      False         False     False           False     False      False       False        True   False      False
1      False    False     False     False      False       False        False      False         False     False            True     False      False       False       False   False      False
2      False    False     False     False      False       False        False      False         False     False           False     False       True       False       False   False      False
3      False    False      True     False      False       False        False      False         False     False           False     False      False       False       False   False      False
4      False    False     False     False      False       False        False      False         False      True           False     False      False       False       False   False      False
5      False    False     False     False      False       False        False      False         False     False           False     False      False       False       False    True      False
6      False    False     False     False      False       False        False      False         False     False           False     False       True       False       False   False      False
7      False    False     False     False      False       False        False      False          True     False           False     False      False       False       False   False      False
8      False    False     False      True      False       False        False      False         False     False           False     False      False       False       False   False      False
9       True    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
10     False    False     False     False      False       False         True      False         False     False           False     False      False       False       False   False      False
11     False    False     False     False      False       False        False      False         False     False           False     False      False        True       False   False      False
12     False    False     False      True      False       False        False      False         False     False           False     False      False       False       False   False      False
13     False    False     False     False       True       False        False      False         False     False           False     False      False       False       False   False      False
14     False    False     False     False      False        True        False      False         False     False           False     False      False       False       False   False      False
15     False    False     False     False      False       False        False      False         False     False           False      True      False       False       False   False      False
16     False     True     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
17     False    False     False     False      False       False        False       True         False     False           False     False      False       False       False   False      False
18     False    False     False     False      False       False        False      False         False     False           False     False       True       False       False   False      False
19     False    False     False      True      False       False        False      False         False     False           False     False      False       False       False   False      False
20     False    False     False      True      False       False        False      False         False     False           False     False      False       False       False   False      False
21     False    False     False     False      False       False        False      False         False     False           False      True      False       False       False   False      False
22     False    False     False     False      False       False        False      False          True     False           False     False      False       False       False   False      False
23     False    False     False     False      False       False        False      False         False     False           False     False       True       False       False   False      False
24     False    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False       True
25     False    False     False     False      False       False        False      False          True     False           False     False      False       False       False   False      False
26      True    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
27      True    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
28     False    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False       True
29     False     True     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
30     False    False     False     False      False       False        False      False          True     False           False     False      False       False       False   False      False
31     False    False     False     False      False       False        False      False         False     False           False     False      False       False       False   False       True
32     False    False     False      True      False       False        False      False         False     False           False     False      False       False       False   False      False
33     False     True     False     False      False       False        False      False         False     False           False     False      False       False       False   False      False
34     False    False     False     False      False       False        False      False         False     False           False      True      False       False       False   False      False
35     False    False     False     False      False       False        False      False          True     False           False     False      False       False       False   False      False

,Car_Audi,Car_BMW,Car_Fiat,Car_Ford,Car_Honda,Car_Hundai,Car_Hyundai,Car_Mazda,Car_Mercedes,Car_Mini,Car_Mitsubishi,Car_Opel,Car_Skoda,Car_Suzuki,Car_Toyoty,Car_VW,Car_Volvo
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
8,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
9,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
12,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
19,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
22,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
26,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
29,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
32,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
35,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [199]:
#Independent Variable:
X2=pandas.concat([data_co2[['Volume','Weight']],ohe_data_co2],axis=1)
#Dependent Variable
y=data_co2['CO2']

In [201]:
X2

,Volume,Weight,Car_Audi,Car_BMW,Car_Fiat,Car_Ford,Car_Honda,Car_Hundai,Car_Hyundai,Car_Mazda,Car_Mercedes,Car_Mini,Car_Mitsubishi,Car_Opel,Car_Skoda,Car_Suzuki,Car_Toyoty,Car_VW,Car_Volvo
0,1000,790,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
1,1200,1160,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,1000,929,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
3,900,865,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,1500,1140,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
5,1000,929,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
6,1400,1109,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
7,1500,1365,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
8,1500,1112,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
9,1600,1150,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,1100,980,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
11,1300,990,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
12,1000,1112,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
13,1600,1252,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
14,1600,1326,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
15,1600,1330,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16,1600,1365,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,2200,1280,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
18,1600,1119,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
19,2000,1328,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
20,1600,1584,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
21,2000,1428,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
22,2100,1365,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
23,1600,1415,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
24,2000,1415,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
25,1500,1465,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
26,2000,1490,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,2000,1725,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
28,1600,1523,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
29,2000,1705,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,2100,1605,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
31,2000,1746,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
32,1600,1235,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
33,1600,1390,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,1600,1405,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
35,2500,1395,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False

In [203]:
#Training
from sklearn import linear_model
mlr1=linear_model.LinearRegression()
mlr1.fit(X2,y)

LinearRegression()

In [209]:
#we can predict the CO2 emissions based on the car's weight, volume, and VW ma
predictedCO2_scale=mlr1.predict([[2300,1300,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False]])
print(predictedCO2_scale)

[122.45153299]

C:\Users\sayde\New folder\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

# Reflection (Samantha I. De Jesus)

This activity has taught me how to manage and assess raw data easily. I've had a hands-on opportunity to dive deeper into the essentials in our on-going project regarding artificial intelligence (AI) and machine learning through the use of Python programming and Jupyter Notebok. It is indeed time-consuming for us, humans, to inspect each and every variable when conducting an experiment. That's why I became interested in understanding these techniques to be more efficient when dealing with large data sets. By doing this activity, I gained knowledge on how to handle missing values, standardize values, and transform data for accurate use in machine learning. Also, I've explored some of the Python libraries, such as Pandas, NumPy, and linear models, to efficiently manipulate data. 

As a summary, this activity was fun. It didn't only strengthen my programming skills but also deepened my understanding about the applications of data science. I hope that I will be able to apply these experiences in the future.

# Reflection (Sebastian D.V. Partosa)

When we worked on data cleaning and processing in Jupyter, it felt like I was organizing a messy room. At first, the dataset was chaotic—missing values here, weird duplicates there—it was like stepping into a space that desperately needed attention. But as I started coding, piece by piece, things began to make sense. This activity taught me that coding isn’t just about writing lines of instructions; it’s about problem-solving. Each step, whether removing duplicates or standardizing values, required logic and attention to detail. And honestly, seeing the dataset transform into something structured and useful gave me a sense of accomplishment. What I loved most about this exercise was how it emphasized the importance of the little things. Small tweaks in the code made a big difference in the output. It reminded me that sometimes, even in life, solving a big problem means focusing on the small steps first.
    
Overall, this activity wasn’t just about cleaning data—it was about learning patience, precision, and the satisfaction that comes from creating order out of chaos.